services:
  portfolio:
    image: iamthewraith/wraithcode:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3009:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
